name: Production CI - Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        environment: Production
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Install Yarn
              run: corepack enable
            - name: Install modules
              run: yarn install
            - name: Build project
              run: yarn build
            - uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: |
                yarn install --non-interactive
            - name: Deploy to Vercel Action
              uses: BetaHuhn/deploy-to-vercel-action@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  ALIAS_DOMAINS: 'toxicitycheck.vercel.app'
                  PRODUCTION: true
                  GITHUB_DEPLOYMENT_ENV: Production
                  FORCE: true
